### ISSUE TITLE
Create the tracker data.

### ISSUE THREAD

**Issue by popstick** [BraunPhilipp/sentiment-analyzer#1]
Hi Philipp. Can't figure out how to generate the data for the trackers table. Any clues?

**Comment by BraunPhilipp** [comment]
'trackers' is a table which contains all the keywords which are searched for on twitter. These keywords can be added using the Rest API or by populating the table with seed data. Hope it helps.

**Comment by popstick** [comment]
Got it. Thanks very much. Cool app.
